mode: parallel
containers:
  - address:  #青龙2.2、青龙2.8、v1v2v3v4v5访问地址（根据自己ip填）
    username:  #用户名 青龙2.2、青龙2.8、v1v2v3v4v5账号（根据自己面板后台填）
    password:  #密码 青龙2.2、青龙2.8、v1v2v3v4v5密码（根据自己面板后台填）
    weigth:  
    mode: parallel
    limit: 9999 #限制容器ck数目
theme: https://ghproxy.com/https://raw.githubusercontent.com/cdle/xdd/main/theme/kuduan.html #自定义主题，支持本地、网络路径（本地文件在/xdd/xdd/theme/kuduan.html，自行测试主题）
static: ./static #静态文件 便于自定义二维码页面时，引入css、js等文件（不用动）
master: jd_xxxxx #管理员账户pin，有多个用'&'拼接（访问ip:8080/admin使用）
database:  #数据库位置 #（强迫症的我还是给它找了个家 不用动）
qywx_key:  #企业微信推送key（这个就是企业微信机器人的key）
daily_push: #定时任务（这个我暂时没有配置）
resident: #均衡模式下所有容器共同的账号pin，有多个用'&'拼接。不建议填写，后续实现指定账号助力功能。（这个我也没配置，多容器自己试试）
user_agent:  #自定义ua 暂时用不到
telegram_bot_token:  #telegram bot token（这个应该不用再说了吧，国外服务器专用）
telegram_user_id:  #telegrame user id（这个应该不用再说了吧，国外服务器专用）
qquid:  #接收通知的qq号（这个填你的QQ）注意格式前后都有空格 示例|qquid: 123456 #
qqgid: #监听的qq群（把你的羊毛群号填上去）注意格式前后都有空格 示例|qqgid: 3 #
qbot_public_mode: true #qq机器人群聊模式，（私聊模式改成：false）
default_priority:
no_ghproxy: true 
daily_asset_push_cron:
repos:
  - git: https://github.com/shufflewzc/faker2.git


